name: ASP.NET Core API Code Style Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Укажите актуальную версию .NET SDK

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Install StyleCop.Analyzers
      run: dotnet tool install --global StyleCop.Analyzers
      
    - name: Run StyleCop analysis
      run: dotnet stylecop analyze --no-build --verbosity quiet